version: '2'

services:
  vt-assets:
    container_name: vt-assets
    build: '.'
    volumes:
      - ./src/assets:/var/www/html/assets:rw
      - ./config/sites-available:/etc/apache2/sites-available:rw
    ports:
      - "4201:80"